config/routes.rb
Kittyapp::Application.routes.draw do
  root :to => 'home#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :home, only: [:index]

  resources :kitties do
    resources :comments
  end
 

  resources :votes, only: [:new, :create]

  

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  description      :text
#  commentable_id   :integer
#  commentable_type :string(255)
#  ancestry         :string(255)
#  kitty_id         :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ActiveRecord::Base
	belongs_to :kitty
	belongs_to :user
	has_ancestry
	attr_accessible :parent_id, :description, :kitty_id
end

app/models/kitty.rb
# == Schema Information
#
# Table name: kitties
#
#  id          :integer          not null, primary key
#  link        :string(255)
#  description :text
#  user_id     :integer
#  image       :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Kitty < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :votes
	attr_accessible :link, :description, :user_id, :image, :remote_image_url
  mount_uploader :image, ImageUploader


  def up_votes
    votes.select{|vote| vote.up }
  end

  def down_votes
    votes.reject{|vote| vote.up }
  end

  def aggregate
    up   = self.up_votes.size
    down = self.down_votes.size
    up - down
  end

  def time_ago
    (self.created_at - Time.now) / 60
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base

  attr_accessible :username, :password

  validates :username, presence: true
  validates :password, presence: true
  validates :username, uniqueness: true
  has_secure_password
  has_many :kitties
  has_many :votes
  has_many :comments

end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id       :integer          not null, primary key
#  up       :boolean
#  user_id  :integer
#  kitty_id :integer
#

class Vote < ActiveRecord::Base
	validates :user_id, :uniqueness => true
	belongs_to :kitty
	belongs_to :user
  attr_accessible :up, :user_id, :kitty_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery

	def authenticate!
		redirect_to root_path unless current_user
	end

	def login(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find session[:user_id] if session[:user_id]
	end

	helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	# def index
	# 	@comments = Comment.scoped
	# 	@comment = Comment.new
	# end

  def new 
    ap params
    @kitty = Kitty.find(params[:kitty_id])
  	@comment = Comment.new(parent_id: params[:parent_id], kitty_id: params[:kitty_id])
  end

  def create
    ap params
  	@comment = Comment.new(params[:comment])
    @comment.kitty_id = params[:kitty_id]
    @comment.user_id = session[:user_id]
  	if @comment.save
  	  redirect_to kitty_path(@comment.kitty)
  	else
  		render :new
  	end
  end

  # def destroy 
  # 	comment = Comment.find(params[:id])
  # 	comment.destroy
  # 	redirect_to comments_path
  # end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @kitty = Kitty.all.reverse
  end
end

app/controllers/kitties_controller.rb
class KittiesController < ApplicationController

	def new
	  @kitty = Kitty.new()
	end

	def show
    @kitty = Kitty.find(params[:id])
     #this is setting up the new comment form
    @comment = Comment.new(parent_id: params[:parent_id])
	end

	def create
		@kitty = Kitty.create!(params[:kitty])
		@kitty.user_id = session[:user_id]
		@kitty.save!
		redirect_to :root
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.find_by_username(params[:username])
    @user = session[:user_id]
  end

  def create
    @user = User.find_by_username(params[:username])

    if @user && @user.authenticate(params[:password])
      @user = session[:user_id]
      flash[:success] = "Welcome, #{@user.username}!"
      redirect_to root_path #action: 'show', id: @user.id
    else
      flash[:notice] = "An error occured, please try again."
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def create
    @user = User.new(params[:user])
    if 
      @user.save
      login(@user)
      flash[:notice] = "Success"
      redirect_to :root
    else 
      flash[:notice] = "An error occured, please try again."
      render :new
    end

  end


  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    # redirect_to
  end



end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def create
		up = params[:up] =~ /^t/ ? true : false
	  @vote = Vote.create!(up: up, user_id: session[:user_id], kitty_id: params[:kitty_id])
		@vote.save!
		render :json => { :new_count => up ? @vote.kitty.up_votes.count : @vote.kitty.down_votes.count }
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
    end.join.html_safe
  end
end

app/helpers/kitties_helper.rb
module KittiesHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
.comment
	.user_name=comment.user.username
	.created_at=comment.created_at.strftime("%B %d, %Y")
	.description=comment.description
	.actions
		=link_to "Reply", new_kitty_comment_path(:parent_id => comment.id, kitty_id: @kitty.id)
		

app/views/comments/_comments.html.haml
-@comments.each do |comment|
	%h3
		=comment.description
	%p
		="by: #{comment.user.username},"
		="#{comment.created_at} ago"

app/views/comments/_form.html.haml
=form_for [@kitty, @comment] do |t|
	=t.hidden_field :parent_id
	=t.text_area :description, rows: 6
	%p=t.submit

app/views/comments/index.html.haml
=nested_comments @comments.arrange(order: :created_at)
=render "form"

app/views/comments/new.html.haml
=render @comment.parent if @comment.parent

=render 'form'

app/views/comments/show.html.haml
=nested_comments @comment.subtree.arrange(:order => :created_at)

app/views/home/index.html.haml
-@kitty.each do |kitty|
	.whole_kitty
		.kitty_object
			.thumb_image
				=image_tag kitty.image_url(:thumb).to_s
			.kitty_info
				=kitty.link
				.description=link_to kitty.description, kitty_path(kitty.id)
				.kitty_details
					%p="By: #{kitty.user.username}"
					%p="created: #{kitty.time_ago.to_s} minutes ago"
					%p="#{kitty.comments.count} comments"
			.vote_information
				.down_vote
					=link_to image_tag("down_arrow.gif"), votes_path({kitty_id: kitty.id, up: false}), method: :post, remote: :true
				.aggregate_vote
					="#{kitty.aggregate}"
				.up_vote
					=link_to image_tag("up_arrow.gif"), votes_path({kitty_id: kitty.id, up: true}), method: :post, remote: :true

app/views/kitties/new.html.haml
.new_kitty
	=form_for @kitty, :html => {:multipart => true} do |t|
		=t.label :link
		=t.text_area :link, placeholder: "link to image", cols: "60", rows: "1"
		%p OR
		=t.file_field :image
		=t.label :description
		=t.text_area :description, cols: "60", rows: "6"
		=t.submit

app/views/kitties/show.html.haml
.kitty_profile
	.kitty
		=@kitty.description
		%p="Posted By: #{@kitty.user.username}"
		%p="Total Votes: #{@kitty.aggregate}"
		=@kitty.link
		.kitty_image=image_tag @kitty.image_url(:medium).to_s

	//=render @comment.parent if @comment.parent
.kitty_comments
	=render '/comments/form'
	=nested_comments @kitty.comments.arrange(order: :created_at)

app/views/layouts/_navigation.html.haml
%nav
	.logo
	.forever_nav
		=link_to "Home", root_path
		=link_to 'New Kitty', new_kitty_path
	.user_nav
	- if current_user
		=link_to 'logout', session_path(current_user), method: :delete
		=link_to current_user.username, user_path(current_user.id)
	- else 
		=link_to 'Login', new_session_path
		=link_to 'Create', new_user_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Kitty App
    %link{href: 'http://fonts.googleapis.com/css?family=Droid+Sans:400,700', rel: 'stylesheet', type: 'text/css'}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render "/layouts/navigation"
    .main
      - if flash[:notice]
        .notice=flash[:notice]
      = yield

app/views/users/_form_user.html.haml
=form_for @user do |f|
  =f.label :username
  =f.text_field :username, :placeholder => "username"
  =f.label :password
  =f.password_field :password, :placeholder => "password" 
  =f.submit

app/views/users/create.html.haml
.create_user
  =render "form_user"

app/views/users/new.html.haml
= render "form_user"

app/views/users/show.html.haml
%h2="Welcome #{@user.username}"
-@user.kitties.each do |kitty|
	.whole_kitty
		.kitty_object
			.thumb_image
				=image_tag kitty.image_url(:thumb).to_s
			.kitty_info
				=kitty.link
				=link_to kitty.description, kitty_path(kitty.id)
				%p="By: #{kitty.user.username}"
				%p="created: #{kitty.time_ago.to_s} minutes ago"
				%p="#{kitty.comments.count} comments"
			.aggregate_vote
				="Aggregate Votes:#{kitty.aggregate}"
			